Repository CruGlobal/ab-utils, pull requests merged in 2023-02, with the labels that each got.

#40 Prevent Port Conflict
  utils/controller.js
Labels: patch

#42 Provide a default `*.healthcheck` request handler for AB services
  utils/controller.js
  utils/defaultHealthcheck.js
Labels: minor

#43 *Fix [RangeError: Invalid string length] error
  utils/serviceRequest.js
Labels: bug, patch

#44 return the promise
  utils/reqApi.js
Labels: patch
