Repository CruGlobal/ab-utils, pull requests merged in 2023-01, with the labels that each got.

#35 Update metadata in package.json
  README.md
  docs/README.hbs
  package-lock.json
  package.json
Labels: major

#36 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: no_release

#37 Hotfix/service request
  test/unit/serviceRequest.test.js
  utils/serviceRequest.js
Labels: patch

#38 req.ab.notify() should also log messages to the console
  utils/reqNotification.js
Labels: minor

#39 Jh/fix duplicate requests
  test/unit/reqAB.js
  test/unit/reqNotification.test.js
  test/unit/resAPI.test.js
  test/unit/serviceRequest.test.js
  utils/controller.js
  utils/reqNotification.js
  utils/reqService.js
  utils/reqServiceCote.js
  utils/resApi.js
  utils/serviceRequest.js
Labels: minor
